# Generated by Django 5.1.6 on 2025-03-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hotel_name',
            field=models.CharField(default='Hotel name', max_length=522),
        ),
    ]
