# Generated by Django 5.1.6 on 2025-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_payment_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_in',
            field=models.DateTimeField(default='2025-02-20'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_out',
            field=models.DateTimeField(default='2025-02-25'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='hotel_name',
            field=models.CharField(max_length=522),
        ),
    ]
